### ISSUE TITLE
Memory limit issues and timeouts

### ISSUE THREAD

**Issue by roborourke** [felixkoch/PHP-FaceDetector#1]
Hi Felix,

I was trying this out for a WordPress integration but ran into problems with memory limits and timeouts. Do you have any ideas on how to get around this?

**Comment by AlexanderMatveev** [comment]
@roborourke give some examples please, with source images and hardware info

**Comment by roborourke** [comment]
Wow I posted this a while back! Was able to work around the specific limitations at the time using background/ CLI processes. I think if anything all that’s required is to suggest a recommended image size for performance. Will close the issue
